### ISSUE TITLE
Can't reply to a post, captcha doesn't seem to work

### ISSUE THREAD

**Issue by fighuass** [zixaphir/appchan-x#1007]
When I reply to a post, I click the captcha button, do what I need to do until it gets a check mark, and then press submit. However, when I do that, nothing gets posted. The captcha seems to reset as if it's never been done. Any fix for this?

**Comment by plabuda** [comment]
I just turned 4chanX off on Opera, and captchas still won't go through. I think something on 4chan's side might have been broken

**Comment by fighuass** [comment]
+1

I'm also running Opera, also disabled 4chan X and indeed, it still won't work.

Tried posting again today, it works again. No idea why, I didn't do anything. Case closed, I guess.
