### ISSUE TITLE
The return of /pol/ alt-flags.

### ISSUE THREAD

**Issue by f00fcat** [zixaphir/appchan-x#1009]
Anyone have a quick hackjob to rig the flag selector dropdown into QR? I guess I'll try to do it myself later, but I've never actually worked with any 4chan modding before since AppchanX always had everything I needed.
![flagselector](https://user-images.githubusercontent.com/29531063/27270169-fc2ce80c-5481-11e7-8766-defc980a49be.png)

**Comment by neau** [comment]
https://github.com/zixaphir/appchan-x/issues/454
