### ISSUE TITLE
Error: Specified Thread does not exist

### ISSUE THREAD

**Issue by PaganJoe** [zixaphir/appchan-x#533]
This randomly happens when I'm trying to respond to a thread from the front page. I haven't tried going back pages to check but when infinite scrolling was on, it was also happening. I've also noticed that if I go to a different board, whatever is in the postbox stays in the postbox, as if I didn't just load a new page. It's kinda weird.

Hm, I noticed that if I get that error and try going to another board, it won't let me respond to a post. It'll act as if I'm trying to start a new thread with whatever was left in the post. It only fixes itself when I refresh the page or go to another tab.

Firefox 26.0
Appchan-x 2.8.1

I'd check and post errors but don't know where the error console went. Oh and this started happening during yesterday's update. 

And after playing around with 4chan, it seems like whenever I go to a new board, it loads it in a weird way. It like "slides" instead of the loading normally and I think that might be what causes the problem.

I say "slide" because the tab doesn't show it loading just that it changes name, the post info stays the same, and the error message didn't go away, as if the UI just slid over to the next board. I don't know if that makes sense to anybody else but thought I should add it.

**Comment by RagnarokVorkel** [comment]
It's back.

**Comment by RagnarokVorkel** [comment]
/g/ board

**Comment by ccd0** [comment]
@RagnarokVorkel
That was 4chan going down.
