### ISSUE TITLE
Appchan not installing

### ISSUE THREAD

**Issue by b4xtrr** [zixaphir/appchan-x#821]
Hey. I'm not sure what the hell is going on. It was working just fine until i accidentally updated firefox to the lastest version, and then i downgraded back to 28. I installed greasemonkey and appchan but... nothing really changes? is it because the current appchan is not compatible with ff 28 anymore?

**Comment by zixaphir** [comment]
You probably need to use an older version of GreaseMonkey. 1.15 works on PaleMoon.
