### ISSUE TITLE
Gallery fit width doesn't work

### ISSUE THREAD

**Issue by bno1** [zixaphir/appchan-x#824]
Gallery doesn't fit the images to page width when enabled. Fit height works as expected.

![2014-11-14-234651_1147x1042_scrot](https://cloud.githubusercontent.com/assets/6632595/5054000/0e9c6080-6c59-11e4-88f2-981ba8a45dcd.png)

**Comment by zixaphir** [comment]
Alright, this seems to be an issue with how newer versions of Firefox calculate max-width in flex containers. While the `calc(100vw - 200px)` works, I'd like to find a solution that's a bit less... hacky.

**Comment by ccd0** [comment]
Seeing the same thing in 4chan X.

    .gal-viewport {
      overflow: hidden;
    }
    .gal-image a {
      max-width: 100%;
    }

seems to fix it.

**Comment by zixaphir** [comment]
Thanks @ccd0.
