### ISSUE TITLE
Theme editor make it left and right snappable.

### ISSUE THREAD

**Issue by EraYaN** [zixaphir/appchan-x#825]
I have seen this in older issues with the note "I will change this soon".

But I would still like to be able to drag the theme editor around (to look underneath it). (Snap is left and right would also do)

The wordpress theme editor solves this in an other way.
It moves the page to the left. It also uses a sample page. I don't know how easy it would be to set that up.

**Comment by zixaphir** [comment]
Fixed in next version.
