### ISSUE TITLE
(embed) link location

### ISSUE THREAD

**Issue by EraYaN** [zixaphir/appchan-x#826]
The (unembed) is placed after the embedded video. I would like an option where the (embed) and (unembed) have the same location. (preferably behind the link)

So maybe inject the embedded video/document after the (embed) </a> with a <br> in between. And just keep the link in the text. I find that a more elegant solution then the current one. (I have to move my mouse to unembed again, ooh the horror!)

**Comment by zixaphir** [comment]
There's a new floating embed option that kinda sorta fixes this, but I'll also look into repositioning the embedded element.
