### ISSUE TITLE
Post dropdown menu does not move correctly/closed onScroll

### ISSUE THREAD

**Issue by EraYaN** [zixaphir/appchan-x#827]
When I scroll the menu stays open. Low priority, but a shame none the less.
Closing is one option the other is anchoring it to the posts down arrow.

Screen:
http://imgur.com/qSYfCvh

**Comment by zixaphir** [comment]
I'll look into alternate positioning options / closing on scroll.

**Comment by lurklurk** [comment]
For me it doesn't even show up after it closes. When I hover my mouse in the position nothing happens.
