### ISSUE TITLE
Going back in browser doesn't work

### ISSUE THREAD

**Issue by Preau** [zixaphir/appchan-x#829]
In Chrome sometimes going into a thread from the index in catalog view and then going back using the browser's back button just brings me to the top of the thread and not back to the catalog. 

The URL in the url bar changes (to 'https://boards.4chan.org/board/') to the correct URL but it doesn't seem to try and load the catalog again.

This happens mostly if I've been in a thread for a while, if I go forth and back immediatly it usually works.

**Comment by zixaphir** [comment]
Is this still an issue?

**Comment by Preau** [comment]
Yes still happens

**Comment by zixaphir** [comment]
Alright, I'll have to do some more testing in Chrome. Thanks. :)

**Comment by penandlim** [comment]
yup happens to me too on chrome
