### ISSUE TITLE
Back and forward post links often cease working for no reason

### ISSUE THREAD

**Issue by IonJam** [zixaphir/appchan-x#830]
Using latest version of Firefox and AppchanX. For some reason, even though I activated hashtag navigation, there's no visible hashtag on the link number (if there was supposed to be one), and although at first clicking links and backlinks normally brings me to the post like normal, at seemingly random times it stops working, so clicking links produces absolutely no result until the page is refreshed.

**Comment by zixaphir** [comment]
Is this still an issue?

**Comment by SamuraiSH** [comment]
It seems to be working better for me now.
The only problem with backlinks that I'm having now is clicking on one from the index and not having it snap to the quoted post when the thread opens.
