### ISSUE TITLE
issues with recaptcha

### ISSUE THREAD

**Issue by 1idd0kun** [zixaphir/appchan-x#834]
Even after the recaptcha has been verified correctly, I still can't submit the post. I click submit and nothing happens.

I'm on firefox 26 with greasemonkey 1.15 and appchan x 2.9.40

**Comment by yarrmateys** [comment]
if it does, i hope it's optional. i often add more stuff or reread the post and fix errors after solving the captcha out of a habit.

**Comment by zixaphir** [comment]
This should be fixed.
