### ISSUE TITLE
"Quoted by" links multiply when page is reloaded with 'R' key

### ISSUE THREAD

**Issue by Oddegamra** [zixaphir/appchan-x#835]
Whenever a post is linked by another post, that post ID appears as link in the quoted post's header (I have no idea what the official name of this feature is, so I'll call it "quoted by" links for now). Now, if I reload the index using the "R" key, and the page content changes, the links multiply, that is, duplicated links start appearing. The problem only seems to appear on index pages, not when browsing a single thread.

The attached image shows a random post after four refreshes: ![Can't hold all these links](https://cloud.githubusercontent.com/assets/637610/5363063/f7b70b48-7fd8-11e4-819c-2db47cc3697f.png)

- Firefox 34.0.5 (also in 33)
- Greasemonkey 2.3
- appchan-x 2.9.40
- Default settings (also did reset)
- No other userscript to interfere

**Comment by zixaphir** [comment]
Does this still occur?
