### ISSUE TITLE
Image expansion not snapping back

### ISSUE THREAD

**Issue by Yaanu** [zixaphir/appchan-x#837]
I'm not sure when exactly it happened, but at some point after 2.9.38, image expansions began to not snap back to the original thumbnail. Previously you could click an image to expand it, then click it again to compress it back into a thumbnail and also snap back to that post, preventing you from having to scroll back up to get back to where you were. After 2.9.38, I believe, that functionality was lost, and now you have to scroll back up after compressing an image in order to get back to where you were. Normally this would not be a problem, but with tall vertical images on /co/ in story-time threads this can get annoying very quickly.

Any chance for a fix, or will I just have to deal with it?

**Comment by zixaphir** [comment]
Is this still an issue?

**Comment by Yaanu** [comment]
Not at all, it seems. I noticed it last night; I guess it was fixed along with the rest of the other bugs.
Thanks!
