### ISSUE TITLE
Further anti-adblock annoyances

### ISSUE THREAD

**Issue by brndd** [zixaphir/appchan-x#843]
I explicitly want to see ads on 4chan, so I have whitelisted it in my adblocker and don't have the "Hide ads" features enabled in Appchan.

However, with Appchan enabled I see a "*Please support 4chan by disabling your ad blocker on* \**.4chan.org/*\**, purchasing a self-serve ad, or buying a 4chan Pass.*" message next to every ad banner.

I suppose this is a bug or something.

**Comment by Pikachuy** [comment]
I'm not sure if this needs another topic and seeing how it's related to blocking ads: 

![untitled](https://cloud.githubusercontent.com/assets/4439919/5641092/1d4342c8-95e6-11e4-9c47-75ecb43aca5c.png)

These big boxes (including another at the bottom) just randomly appeared one day. Like brndd said, white listing the site and checking the Hide Ads option don't make any difference.

**Comment by zixaphir** [comment]
Hide Ads should now hide these messages.
