### ISSUE TITLE
Settings menu closes on click

### ISSUE THREAD

**Issue by DaftMoron** [zixaphir/appchan-x#844]
I click the tools button in the upper right corner, click Settings. The moment I click anywhere, even inside the settings window, the menu disappears. Can't scroll either.

2.9.43 on Chrome 39.0.2171.95 m

Edit: Appchan-X doesn't like Nebukazar's fork of OneeChan.

**Comment by zixaphir** [comment]
Oneechan is inherently incompatible with appchan. ;)
