### ISSUE TITLE
Mascot links all broken

### ISSUE THREAD

**Issue by Ndart** [zixaphir/appchan-x#845]
All mascots included in the base script have broken links and do not load correctly. Copying the link and loading the image by itself works but nothing but "Mascot 404" ever shows up on boards. This has been a constant issue for several months now and seems to be related to how minus links work so I'm not sure if it can be fixed without just rehosting all the images but I figured it was worth bringing to attention nonetheless.

**Comment by zixaphir** [comment]
Works for me. Might possibly be related to your browser's security settings (cross domain SSL ftw).

Also, minus sometimes breaks, but it's never been a constant issue in my experience.

**Comment by anonymau5** [comment]
Mine did the same for about a week but now they work fine.

**Comment by zixaphir** [comment]
Closing this because it doesn't seem to be an appchan issue.
