### ISSUE TITLE
Captcha disappearing 

### ISSUE THREAD

**Issue by Verty** [zixaphir/appchan-x#847]
Not sure if this is just me, but about 60% of the time, after clicking the robot box, the captcha disappears, and when you click the box again, the spinny circle loads indefinitely until a refresh, after which most of the time it happens again.  It doesn't seem to happen using vanilla 4chan. 
Anyone else getting this?

**Comment by ccd0** [comment]
There were some problems with detecting when the QR was focused (and should not be autohidden) when Zixaphir merged the captcha stuff from my fork.  At the time I was working around it by holding the QR open whenever the captcha was open, but it seems that workaround didn't make it into Appchan.  In any case, the focus detection problems are more or less fixed now, so another merge would fix this issue.

**Comment by zixaphir** [comment]
Should be fixed.
