### ISSUE TITLE
Exlinks not compatible?

### ISSUE THREAD

**Issue by temp9** [zixaphir/appchan-x#850]
Im not sure if this is a problem with exlinks or appchanx, but when i have both installed exlinks doesn't show up.
There is no way to access exlinks settings, no reverse image search, and no exhentai link formatting.

Tried in both firefox and chrome with the same results.
Exlinks does work though using the native 4chan extension instead of appchanx.

Here is what the console popped up in chrome
![untitled](https://cloud.githubusercontent.com/assets/10510650/5716602/873b05d4-9aa6-11e4-810f-49b916810165.png)

**Comment by zixaphir** [comment]
I'll look into the Firefox issue, but Appchan X isn't compatible with TamperMonkey.

**Comment by Schuuby** [comment]
I had issues with it, too. Try to comment out line 1432 of Exlinks. Fixed it for me.
![0b0ab4411d](https://cloud.githubusercontent.com/assets/3997574/5794081/be1b6726-9f5e-11e4-95c9-9de0f1cb942c.png)

**Comment by zixaphir** [comment]
https://github.com/Hupotronic/ExLinks/issues/56

**Comment by zixaphir** [comment]
Looks like @daiz fixed it.
