### ISSUE TITLE
Can't submit a new post / Start a new thread

### ISSUE THREAD

**Issue by kdu3142** [zixaphir/appchan-x#852]
I honestly don't know if this is a bug, or if I'm doing something wrong...

But every time I reply to an already existing thread, everything works as it should.

But if I try to start a new thread, when I click the submit button, nothing happens. I've changed the position, a lot of the setting and it doesn't work. If I disable Appchan-x it works.
What's up?

EDIT: After looking at screenshots of the app, I can say that I actually don't have the "Start new thread" Link. So, I'd have to fix that...

**Comment by bxte** [comment]
Since last update I can post in a thread but I cannot open a New Thread. Same issue?

**Comment by arilsonsilva** [comment]
Im having the same problem while browsing /f/. This message shows up.

"Quick Reply dialog creation crashed.
TypeError: Cannot set property 'innerHTML' of undefined"

**Comment by kdu3142** [comment]
I was trying to use the Quick reply box to make new threads. After failing several times, I searched a little bit and saw a pic where the "Start a thread" button/link was on top of the page. So, I'm assuming I should have that link, but don't.

Or, if I'm supposed to use QR, it's not working, but I get no error messages.
