### ISSUE TITLE
Unread post count and time since posted not updating properly

### ISSUE THREAD

**Issue by Rahmeesh** [zixaphir/appchan-x#855]
Since the update the unread post amount on my tabs won decrease despite me passing over all the posts. I'm not sure if it's related but the timer since a post was made is not displaying anymore either.

**Comment by zixaphir** [comment]
I can't duplicate the Unread post count not updating. Can you post your settings, browser, and browser version?

**Comment by Merrooowwn** [comment]
Having the same issue. Began immediately after the update.

**Comment by Yaanu** [comment]
I'm experiencing this too. I believe it begins after you make a post; when you make a post, the Unread post counter stops decreasing and only grows from there. Essentially, it's no longer "unread posts" and now it is "# of posts made after your first post in the thread".

**Comment by Verty** [comment]
I can't see my page stats at all since the update. And the times on post changed to the actual time rather than "2 hours ago" etc. 
Error upon refresh: "Thread Stats" initialization crashed.
ReferenceError: statsTitle is not defined

**Comment by zixaphir** [comment]
This should be fixed now.
