### ISSUE TITLE
Mascot image quality worsened, board name / banner no longer appearing and blank update number.

### ISSUE THREAD

**Issue by Boldwin** [zixaphir/appchan-x#856]
I'm not positive, correct me if I'm wrong, but before the latest update there seemed to be some sort of feature built into Appchan x that would allow it to automatically tidy up mascots and make them look far more crisp and polished while also cutting out some minor leftover fragments born from my shoddy editing skills. After this update that seems to no longer be the case and a solid portion of my mascots look considerably worse as a result of it.

The "Board title" and "4chan banner" options seem to still function as they create blank space in the positions that I set them to but no title or banner appears where they should be.

Also, in all instances where the update number should normally be is instead completely blank, including exported settings files.

I attempted to reinstall Appchan but it failed to fix any of the issues and wouldn't even allow me to import my settings, causing me to have to restore an older Firefox profile to get it back to how I had it.

This was done on Firefox 35.0

Tested it further on the latest version of Chrome: It allows me to import my settings that I exported from Firefox (Still can't import settings on Firefox, "Import failed due to an error") and the mascot quality is actually at its original clarity on Chrome but still fails to display the board name, banner or update number.

Edit: Turns out toggling "Mascots overlay posts" option actually fixed the quality issue, the others still remain.

**Comment by Boldwin** [comment]
Original post was using Firefox 35.0 but received the same results on the latest version of Chrome.

**Comment by weeb-lord-420** [comment]
I can confirm that the board title and banner are gone from mine, and every time I open a thread, the blank update appears.

**Comment by zixaphir** [comment]
I have no idea what could be causing the mascot quality issue.

Everything else should be fixed in the next version.

**Comment by Boldwin** [comment]
Got the update and everything looks good to go, keep up the good work, thanks a bunch.

Whatever caused the mascot quality issue seems to get fixed by just toggling some of the mascot options on and off which causes it to refresh its analysis of them or something like that. Good enough for me.
