### ISSUE TITLE
Embedded links appear twice

### ISSUE THREAD

**Issue by rhino36** [zixaphir/appchan-x#857]
I don't know if it's me doing something wrong, but embedded links (IE youtube videos) show up twice
![example](https://cloud.githubusercontent.com/assets/7881445/5751062/0df9f57c-9c2c-11e4-8f63-ea524864e04d.png)
This is what it looks like.

**Comment by rhino36** [comment]
Nevermind, I found a workaround. I deactivated the linkify option and kept my 4chan media player on

**Comment by zixaphir** [comment]
Sorry, the two are not compatible, but I'm glad you found a workaround.
