### ISSUE TITLE
Can't create threads

### ISSUE THREAD

**Issue by Merrooowwn** [zixaphir/appchan-x#858]
Since the update, I can't create new threads. If I try, upon submitting, the orange hint dialog box at the top of the page opens saying "You can't reply to this thread anymore."

Interface that I'm using doesn't matter either; catalog, paged, it all gives the same result.

**Comment by zixaphir** [comment]
Let me know if this is still an issue.

**Comment by orrazib** [comment]
I think this was a native 4chan issue, I faced it for a while but it went away before I could check with vanilla 4chan
