### ISSUE TITLE
Theme import and creation broken

### ISSUE THREAD

**Issue by ILoveYou4ever** [zixaphir/appchan-x#861]
It's currently not possible to import a theme (clicking the button does nothing).

FF 35.0, GM 2.3, Appchan X 2.10.1

Edit: Disabling Adblock Edge fixed the creation, but import still doesn't work.

Edit 2: Apparently only once, then it doesn't work again even though Adblock is still disabled.

**Comment by zixaphir** [comment]
I fixed theme importing, but cannot duplicate the theme creation issue.
