### ISSUE TITLE
Unread Post Counter Not Updating

### ISSUE THREAD

**Issue by thatguythathasproblems** [zixaphir/appchan-x#863]
Using the latest version of Chrome and the latest version of AppChan X.

Whenever a new post is made in the thread the unread counter changes to however many posts have been made in the thread. Refreshing sets it back to 0 until someone makes a new post, when it then goes right back to however many posts were in the thread.

**Comment by shugo589** [comment]
I am on Firefox 34 and latest appchan and my unread posts also never get marked as read anymore.

**Comment by Chibicon** [comment]
Same issue.

Firefox Nightly 38.0a1

**Comment by zixaphir** [comment]
Let me know if this is still occurring.

**Comment by thatguythathasproblems** [comment]
Fixed on my end.

**Comment by thatguythathasproblems** [comment]
And now it's all fixed. Thanks.
