### ISSUE TITLE
Favicon does not update to reflect read replies

### ISSUE THREAD

**Issue by swablueme** [zixaphir/appchan-x#864]
I've noticed that on busy threads the icon does not seeem to update: the number of unread replies keeps increasing and the quoted marker (exclamation point) appears to be stuck. Refreshing the page or navigating away causes the icon to momentary vanish however after a few minutes the same stuck issue reoccurs.

**Comment by orrazib** [comment]
Same here using FF 35

If you refresh and manually scroll the page using the mouse it usually corrects itself. But needs to be fixed

**Comment by zixaphir** [comment]
Ensure you're on 2.10.3.
