### ISSUE TITLE
Can't import very large json settings in firefox

### ISSUE THREAD

**Issue by throwaway002** [zixaphir/appchan-x#889]
I'm using this script here to generate a list of locally-hosted mascots.
http://pastebin.com/Sk1UytGC
(fyi, I'm using mix-blend-mode: multiply to use these jpg images, but I digress.)

It fails when trying to load this large json object through the import function.
http://a.pomf.se/kvsqoq.json
with the message, "Import failed due to an error".

The console says:
"$.clear@file:///home/tux/.mozilla/firefox/04wk5cde.default/gm_scripts/appchan_x/appchan-x.user.js:3100:17
Settings.loadSettings@file:///home/tux/.mozilla/firefox/04wk5cde.default/gm_scripts/appchan_x/appchan-x.user.js:19197:1
Settings.onImport/reader.onload@file:///home/tux/.mozilla/firefox/04wk5cde.default/gm_scripts/appchan_x/appchan-x.user.js:19178:1
"

This succeeds in chromium 40. I'm using Firefox 36.0 amd64 from the ubuntu repo with the latest appchan.

**Comment by ccd0** [comment]
It's probably https://github.com/greasemonkey/greasemonkey/issues/2033, in which case updating to the [beta version](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/#version-3.0beta1) of Greasemonkey should fix it.

**Comment by throwaway002** [comment]
Yes, that fixed the issue.
