### ISSUE TITLE
open all threads doesn't scroll to first unread message

### ISSUE THREAD

**Issue by jfessard** [zixaphir/appchan-x#892]
I open all threads, none of the threads will scroll down to the last read message.

If I open a watched thread by left clicking on its name, it will open and get to the first unread if I have tab focus. Without tab focus it will just open at the top/first message.

Expected: with or without focus, threads should scroll to first unread when opened from the thread watcher, individually or by "all threads" link.
Browser: Firefox 36.0.1, Greasemonkey 3.0, appchan 2.10.4

**Comment by fessard** [comment]
The bug still happens when I reset my settings and it seems to behave the same in Chrome+tampermonkey, not scrolling down when not in focus. Does anyone see the same behavior?
