### ISSUE TITLE
File Size limit on /wsg/ incorrect.

### ISSUE THREAD

**Issue by anonymau5** [zixaphir/appchan-x#898]
The maximum file size allowed on /wsg/ is 4096K.
![snapshot 764](https://cloud.githubusercontent.com/assets/2172796/6916526/d93d36a8-d751-11e4-9e4d-926c06fef39f.png)

**Comment by VelocityRa** [comment]
I'd also like this to be fixed.

**Comment by VelocityRa** [comment]
Your file was over the size limit anyway OP (4096KB), but the bug's still there.

**Comment by VelocityRa** [comment]
Nevermind, I fixed it.
