### ISSUE TITLE
Issue with captcha

### ISSUE THREAD

**Issue by thatguythathasproblems** [zixaphir/appchan-x#899]
using the latest version of both Chrome and Appchan X

an error occurred: An internal error occurred: 5129A238971F8.A80A70E.83006310

![error](https://cloud.githubusercontent.com/assets/6742321/6926798/b1a277ec-d7b6-11e4-8408-b4bb0666a5bc.png)

**Comment by MistahK** [comment]
Also having that problem but I don't think it's appchan x because captcha still doesn't work after disabling appchan. I thought I was the only one but since I'm not, it's probably just 4chan.

Posting works fine from my phone

Seems some people can still post though

**Comment by thatguythathasproblems** [comment]
Yeah, looks like it was a problem with 4chan. Closing.
