### ISSUE TITLE
Clock/Post timer wrong; new posts show as "2 hours ago".

### ISSUE THREAD

**Issue by EpikEnvy** [zixaphir/appchan-x#904]
http://puu.sh/hmrY4/6cf21d9094.jpg

For reference, these posts were made 10-15 minutes ago, not two hours ago. I've reset the settings, even redownloaded my browser.

**Comment by ccd0** [comment]
Check your time zone setting.

**Comment by EpikEnvy** [comment]
Oh fuck me, clock was reading correct but the time zone itself was actually wrong, threw me for a loop.
