### ISSUE TITLE
Quote threading and replies to OP

### ISSUE THREAD

**Issue by Ithilion** [zixaphir/appchan-x#907]
Any reason why replies to OP are not threaded? Or maybe it's bugged for me, dunno.
Example:
![untitled](https://cloud.githubusercontent.com/assets/3318892/7291544/28d12de4-e992-11e4-93ba-c2eb23571d89.png)
Shouldn't that reply be threaded?

**Comment by ccd0** [comment]
Every reply is a reply to the OP, link or no link.

**Comment by Ithilion** [comment]
I understand that, but as every reply that quote a single post is indented and moved under the quoted post for, well, threading purposes, shouldn't replies that quote op be indented and moved too? I think that would be more consistent. If it's just me then disregard this.

**Comment by zixaphir** [comment]
Every reply is a reply to the OP, therefore every reply is already "threaded".
