### ISSUE TITLE
Theme broken since today

### ISSUE THREAD

**Issue by Burnyz** [zixaphir/appchan-x#932]
![capture](https://cloud.githubusercontent.com/assets/7921439/9629235/d0bd74aa-5179-11e5-8f60-40a957b33b94.JPG)

I got this weird green background when I booted appchan x today. Also the pages as a whole seem to be loading slower than usual.

**Comment by Burnyz** [comment]
Nvm, figured out the problem. subtlepatterns.com is fucked and it's loading some placeholder background instead.

**Comment by karols146** [comment]
Not only you I have other problem 
http://prntscr.com/8bslse
