### ISSUE TITLE
Mascot 404

### ISSUE THREAD

**Issue by anonymau5** [zixaphir/appchan-x#933]
For some reason, all of the built in mascots are not loading.  
I can still access them by the link directly.
I have cleared all caches that might have been causing issues and the issue persists.
Chrome Version 46.0.2490.13 beta (64-bit)
appchan x 2.10.5

**Comment by anonymau5** [comment]
After a little investigation, it seems the website hosting the images has changed the links from http://i.minus.com/image.png to http://i4.minus.com/image.png

**Comment by nebukazar** [comment]
```
Subject: *.minus.com
Issuer: COMODO RSA Domain Validation Secure Server CA
Expires on: Sep 9, 2015
Current date: Sep 10, 2015
```

The links still work but it looks like they forgot to renew their certificate.

**Comment by anonymau5** [comment]
They haven't worked for a few days now.  Changing them to the updated links fixes it.

**Comment by zixaphir** [comment]
Is this still an issue? It seems to be working fine from here.

**Comment by anonymau5** [comment]
I changed the links to the new ones and it work fine now.  Firefox works fine, Chrome doesn't want to follow the redirection and stops.
