### ISSUE TITLE
JSON navigation does not work properly in chrome

### ISSUE THREAD

**Issue by mahkoh** [zixaphir/appchan-x#934]
The first "go back" or "go forward" is always ignored. After that it works properly.  E.g.

1. Go to http://boards.4chan.org/qa/
2. Go to any thread
3. Reload the page (e.g. press F5)
4. Press the back button
5. The URL changes nothing else happens

This seems to be the problem:

```
    <% if (type === 'crx') { %>
    # blink/webkit throw a popstate on page load. Not what we want.
    popstateHack = ->
      $.off window, 'popstate', popstateHack
      $.on  window, 'popstate', Navigate.popstate

    $.on window, 'popstate', popstateHack
    <% } else { %>
    $.on  window, 'popstate', Navigate.popstate
    <% } %>
```

Removing the popstateHack fixes the problem.

**Comment by mahkoh** [comment]
#885 and #829 are the same issue. Do you remember why you added and this workaround and can you still reproduce the problem?

**Comment by ccd0** [comment]
Blink used to fire a popstate event when the document was loaded the first time, instead of just when using the forward/back buttons to navigate between states of the document.  But this has been fixed:
https://crbug.com/63040
