### ISSUE TITLE
Recaptcha is affected by theme color

### ISSUE THREAD

**Issue by Yoposoc** [zixaphir/appchan-x#939]
So I don't mind recaptcha, but it gets affected by the theme colors and becomes a bitch to see. Is there a way to disable the theme colors just for recaptcha?
![0ca78d64d5 1](https://cloud.githubusercontent.com/assets/2718371/10179288/e94194f2-66b9-11e5-8c7d-9bfe019dd5d1.jpg)

**Comment by zixaphir** [comment]
There's an option for it. I'll disable it by default since it really doesn't work that well anymore.

**Comment by VelocityRa** [comment]
Go to Settings -> Style and uncheck the last option: "Captcha Filter".
