### ISSUE TITLE
Captcha Loading Offscreen

### ISSUE THREAD

**Issue by anonymau5** [zixaphir/appchan-x#952]
Not really sure why but as of today the captcha loads with one third of it off the page.

Google Chrome	47.0.2526.35 (Official Build) beta (64-bit)
Revision	ad0950c1ac32ef02b0b0133ebac2a0fa4771cf20-refs/branch-heads/2526@{#250}
OS	Linux 
Blink	537.36 (@ad0950c1ac32ef02b0b0133ebac2a0fa4771cf20)
JavaScript	V8 4.7.80.17
Flash	19.0.0.226
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.35 Safari/537.36
Command Line	/usr/bin/google-chrome-beta --user-data-dir=/home/user/.config/google-chrome-beta --flag-switches-begin --disable-new-profile-management --enable-scroll-prediction --enable-smooth-scrolling --enable-tab-audio-muting --enable-overlay-scrollbar --flag-switches-end
Executable Path	/opt/google/chrome-beta/google-chrome-beta
Profile Path	/home/user/.config/google-chrome-beta/Default
Variations	47f591a-3f4a17df
52814c1c-f23d1dea
6345b824-3d47f4f4
7c1bc906-8122a015
e9f4800b-39c30599
f1eb96ab-3f4a17df
19f73432-ca7d8d80
76b48ab8-a2567007
31362330-ca7d8d80
c70841c8-4866ef6e
9d315c2-ca7d8d80
1d3ad72e-ec390a18
9e5c75f1-5bfaa58f
f79cb77b-3f4a17df
97dfc274-3f4a17df
ca65a9fe-91ac3782
4ea303a6-3d47f4f4
fa99bb73-3f4a17df
4117e878-96368637
313d831b-e49daded
9736de91-ca7d8d80
5c3cc7b1-3d47f4f4
3ac60855-486e2a9c
ed1d377-e1cc0f14
75f0f0a0-a5822863
e7e71889-e1cc0f14
b39ea213-d1372334
bd368a6b-ca7d8d80

![snapshot 8](https://cloud.githubusercontent.com/assets/2172796/10859611/8d0c181c-7f1c-11e5-81c0-8d8fde96fb51.png)

**Comment by endoflaven** [comment]
Having this as well. Seems to be every captcha. Scrolling right cannot even access the displaced area of the captcha so it cannot be filled or submitted in any way.
appchan x 2.10.13
chrome 46.0.2490.80 m

**Comment by wtbguest** [comment]
For the record, this has been happening to me all week.
Happens off and on, fixes itself randomly on re-opening Firefox.

But a quick fix that might help you and allowed me to post:
Just resize the window -before- you click the Captcha/verification checkmark. You should see the entire Captcha box with all the pictures. If you resize the window to full size after that, the Captcha box will remain in the middle. Have to do this every time you post so it's a pain, but it works for me.

**Comment by anonymau5** [comment]
The best workaround I've found so far is to use the V1 captcha.

**Comment by swablueme** [comment]
Happening to me too.

**Comment by ccd0** [comment]
I had to fix this by watching for the bubble and moving it if it was positioned wrong:
https://github.com/ccd0/4chan-x/commit/1895d5e5890e045e613adf491b1c845105f088a6

The arrow still ends up pointing in the wrong direction, but that's not a big concern.  Does let me know it's still happening, though.

Note that there are currently two versions of the captcha bubble being served, an older one and a newer one, and what you get is random.  The one that has this bug is the newer version, recognizable by the fact that it fades in with a CSS transition.  I personally find the fade-in obnoxious and have overridden it in 4chan X's CSS.

Another way to workaround the issue (from a user perspective) is to disable the sidebar and move the Quick Reply elsewhere.

**Comment by wyrd1234** [comment]
Been using the V1 captchas to get around his problem.  Though now I'm having an issue where it won't accept any "word" captchas, only number ones.

**Comment by ccd0** [comment]
This seems to have been fixed on Google's end now.

**Comment by Zyndrome** [comment]
V1 word captchas are not working at all. No matter how many I solve, it doesn't accept the answer and just moves onto the next one. I have to reload the captcha until I get a number captcha, which is the only thing that works right now.

**Comment by swablueme** [comment]
@Zyndrome That's not a problem. Clear your cookies (or just the google ones) and V1 will work. We've had about 1000 threads about it, on /qa/ it's google's fault.

**Comment by vampiricwulf** [comment]
Looks like this was solved.
