### ISSUE TITLE
Theme Randomly Changed

### ISSUE THREAD

**Issue by thatguythathasproblems** [zixaphir/appchan-x#953]
On 2.10.13 using the latest release of Chrome for my browser, the default "Dark Upgrade" theme suddenly changed and now all links are this disgusting orange color and I can't edit the theme either for some reason to try and change it back.

Before:
![before](https://cloud.githubusercontent.com/assets/6742321/10864699/2fbd8090-7fcd-11e5-8841-446cac39bda3.png)

After:
![after](https://cloud.githubusercontent.com/assets/6742321/10864702/3d421d02-7fcd-11e5-8668-7af51cef8c16.png)

And ALL the themes have had their colored text changed to this color.

Edit: This may or may not be some dumb Halloween thing 4chan is doing.

**Comment by zixaphir** [comment]
It was 4chans Halloween theme. I just decided not to bugger with it since
by the time I got on 4chan, it was near the end of the day.
