### ISSUE TITLE
Open Dialog Pops Up Multiple Times

### ISSUE THREAD

**Issue by anonymau5** [zixaphir/appchan-x#955]
I'm not 100% this is appchan's fault but the only site I've experienced this on is 4chan.
The Open File dialog windows pops up multiple times when attempting to upload an image.  The first image or two it works fine, then after that it proceeds to open immediately after selecting my desired file and then ultimately no uploading the desired file.
I'm using Chrome and forcing the GTK one as the KDE one causes the system to hang on occasion.

**Comment by swablueme** [comment]
Having this issue on Chrome but not on Firefox.

**Comment by nicatronTg** [comment]
I've noticed this behavior with single images, uploading a set of one or more doesn't cause this to happen.

**Comment by nomorenamesleft** [comment]
I am experiencing this as well in Chrome. I haven't tried it in Firefox as i dont use it.

Im relatively certain its Appchan because i dont experience this with other websites or applications.

**Comment by Aftersky** [comment]
I've had this issue for a while so I don't remember when it started. Reverting to build 2.10.7 for now and it seems to work fine in this version.

**Comment by gerakis** [comment]
Also having this issue on chrome for 4chan. Just started a few days ago. When I disabled the appchan extension it worked fine, and when I re-enabled it the problem came back.

**Comment by anonymau5** [comment]
Closing due to the fix performed in https://github.com/zixaphir/appchan-x/issues/957
