### ISSUE TITLE
Download content while in gallery mode [feature request]

### ISSUE THREAD

**Issue by Tegyukfel** [zixaphir/appchan-x#956]
I often browse 4chan in gallery mode. There's a drop-down arrow in the right-upper corner, I think it would be a great place to introduce a Download option, if it is possible.
Like in the drop-down menu that you have at the reply itself -- it has this function. It saves the file in it's original filename.

Of course, I can save it with right-click, but I usually use the Download option if I see a clever image reply, to preserve the filename if I ever want to repost it. Sometimes, the filename makes everything, it's the punchline.

**Comment by ccd0** [comment]
You can download with the original filename by clicking on the filename in the lower right corner.

**Comment by Tegyukfel** [comment]
Whoah, my bad. I didn't know you could do that. Thanks!
