### ISSUE TITLE
Simply Stopped Working Altogether

### ISSUE THREAD

**Issue by FizzTheHuman** [zixaphir/appchan-x#967]
A few days ago, after Windows on my laptop updated (not sure if it's related), AppChan X just stopped working. On or off, it's not showing any effects on 4chan, though it works just fine on my PC. I assume since Chrome syncs my apps between computers that it should behave the same way across all the browsers I use. I've tried disabling and re-enabling it, as well as playing around with 4chan's own settings, but short of uninstalling and reinstalling (since I don't want to lose my settings) I have no idea what to do.

Thanks in advance for any assistance.

**Comment by ccd0** [comment]
Try downloading the extension manually from
https://clients2.google.com/service/update2/crx?response=redirect&prodversion=48.0&x=id%3Dgfibffekgcmgabbfaibbbcapgnfobnoi%26installsource%3Dondemand%26uc
and then dragging and dropping the file you downloaded onto
chrome://extensions

**Comment by FizzTheHuman** [comment]
At first it didn't work, but after disabling and enabling it once more, your answer seems to have done the trick. Many thanks!
