### ISSUE TITLE
Unable to import custom mascots

### ISSUE THREAD

**Issue by Ahegyao** [zixaphir/appchan-x#970]
Hey, so after not fiddling appchan in ages, I decided to do so and ran into a problem of not being able to add my own mascots anymore. Everytime I try to this error message keeps popping up:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by ccd0** [comment]
"Import Mascot" expects a file containing JSON data. I think what you need to use to add your own image is "Add Mascot."

**Comment by Ahegyao** [comment]
You're right. Just goes to show how I've forgotten the ins and outs of this extension. Thanks!
