### ISSUE TITLE
Pages "flashing" and breaking themes

### ISSUE THREAD

**Issue by bonermobile** [zixaphir/appchan-x#990]
Occasionally something will break on page load and themes/CSS will not properly apply in addition to the page contents flashing off and on endlessly. Elements are still there (see attachment) and interactable, you can still scroll, etc but the flashing obscures anything.

I can't consistently replicate this other than refreshing until it happens and it isn't always solved by a refresh either.

![2016-09-24_02-33-02](https://cloud.githubusercontent.com/assets/12283328/18806889/6133fef8-81ff-11e6-847c-c34e8af8102b.png)

**Comment by Temcoin** [comment]
Having this same issue

**Comment by aries1998** [comment]
i have the same problem before i disable adblock plus
